version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: cypress-e2e-tests
      env:
        variables:
          IMAGE: public.ecr.aws/cypress-io/cypress/browsers:node14.19.0-chrome100-ff99-edge
  build-graph:
    - identifier: サンプル Task
      buildspec:  buildspec/sample/task-buildspec.yml
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - cd e2e
      - npm install
  build:
    commands:
      - echo Hello
